### ISSUE TITLE
pod 引入之后 项目内仍然是Use of undeclared type 'ZHRefreshAutoFooter'

### ISSUE THREAD

**Issue by yang19930204** [SummerHF/ZHRefresh#1]

**Comment by SummerHF** [comment]
请问有 import module 么
![screen shot 2018-05-24 at 7 57 47 am](https://user-images.githubusercontent.com/13494694/40457269-33bde40e-5f28-11e8-97ed-e88ea91c38cb.png)
特地测试了下 没有问题

**Comment by yang19930204** [comment]
有的 我pod用其他魔模块都没问题 好尴尬

**Comment by yang19930204** [comment]
pod 'Moya'#请求
  pod 'Alamofire' #Moya基础
  pod 'ObjectMapper' #json 对象
  pod 'SnapKit' #布局
  pod 'ZHRefresh'
  pod 'ETNavBarTransparent' #导航栏透明
  pod 'Eureka'#表单
  pod 'SwiftFCXRefresh'#下拉刷新

我放到前面就好了 可能跟下面的模块冲突

**Comment by yang19930204** [comment]
多谢大佬 可能跟别的模块有冲突 我放到pod最前面就可以了

**Comment by yang19930204** [comment]
![1527189554873](https://user-images.githubusercontent.com/29906145/40507952-85318c80-5fca-11e8-89f6-18bc57417317.jpg)

**Comment by SummerHF** [comment]
你可以这样，新建一个Demo试下 只安装这一个pod, 然后import它, 你也可以点击这个modul 然后搜索下有没有这个类, 我这边操作正常 你这个信息我很难定位问题，报的是文件的权限问题，但是我使用的是public修饰的

**Comment by SummerHF** [comment]
Project > General > Linked Framework and Libraries >
add ZHRefresh
然后
import ZHRefresh
[参考链接](https://github.com/SwiftyJSON/SwiftyJSON/issues/192)

**Comment by yang19930204** [comment]
![1](https://user-images.githubusercontent.com/29906145/40524719-c848eace-600e-11e8-97d1-ead84383b87c.jpg)
是灰色的

**Comment by yang19930204** [comment]
![2](https://user-images.githubusercontent.com/29906145/40524764-03c52266-600f-11e8-92b7-c9d1c15c59d0.jpg)

**Comment by SummerHF** [comment]
我想知道 我提供的Demo程序在你的Xcode运行的起来么  QQ: 391565521 很好奇 @yang19930204

**Comment by SummerHF** [comment]
solved by  `pod install --verbose --no-repo-update`
